#!groovy
try {
    node("master"){
	stage(name: "Aprovao") {
                  echo 'Ignorada a etapa de aprovao para deploy do projeto!'
         }
}
    } catch (Exception e) {
 	
        throw e;
      }

